---
# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

nginx_conf_path: /etc/nginx/conf.d
nginx_vhost_path: /etc/nginx/sites-enabled
nginx_default_vhost_path: /etc/nginx/sites-enabled/default
__nginx_user: "webadm"

#nginx_worker_processes: "2"
nginx_worker_connections: "1024"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_client_max_body_size: "64m"

nginx_proxy_cache_path: ""

nginx_remove_default_vhost: true

nginx_vhosts: true
#
#   # Properties that are only added if defined:
#   error_page: ""
#   access_log: ""
#   extra_parameters: "" # Can be used to add extra config blocks (multiline).

nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   servers: {
#     "srv1.example.com",
#     "srv2.example.com weight=3",
#     "srv3.example.com"
#   }
