---
- name: download certbot-auto
  get_url: url=https://dl.eff.org/certbot-auto dest="{{ ansible_env.HOME}}" mode=a+x
  tags:
    - ssl

#needs to run following commands manually
# $ ~/certbot-auto
# $ ~/certbot-auto certonly --webroot -w /var/www/rails_app/current/public -d somedomain.com -d www.somedomain.com
# $ ~/certbot-auto renew --dry-run
- name: Generate Strong Diffie-Hellman Group
  command: sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  tags:
    - ssl

- name: add cronjob for renew
  cron: name="ssl certificate renew" hour="0,12" job="~/certbot-auto renew --quiet --no-self-upgrade" user=webadm
  tags:
    - ssl
