---
- name: Update apt
  apt: update_cache=yes force=yes
  become: yes
  become_user: root

- name: Install basic dependencies
  apt: pkg={{item}} force=yes
  become: yes
  become_user: root
  with_items:
  - build-essential
  - python-pycurl
  - curl
  - htop
  - git
  - make
  - cmake
  - sqlite3
  - libsqlite3-dev
  - libpq-dev
  - autoconf
  - bison
  - libssl-dev
  - libyaml-dev
  - libreadline6-dev
  - zlib1g
  - zlib1g-dev
  - vim
  - nodejs
  - imagemagick
  - nginx-core
