---
- name: include env vars
  include_vars: "{{ rbenv.env }}.yml"
  tags: rbenv

- include: apt_build_depends.yml
  when: ansible_pkg_mgr == 'apt'
  tags: rbenv

- include: yum_build_depends.yml
  when: ansible_pkg_mgr == 'yum'
  tags: rbenv

- include: dnf_build_depends.yml
  when: ansible_pkg_mgr == 'dnf'
  tags: rbenv

# - include: pacman_build_depends.yml # Arch Linux
#   when: ansible_pkg_mgr == 'pacman'

- include: homebrew_build_depends.yml
  when: ansible_os_family == 'Darwin'
  tags: rbenv

- name: set rbenv_owner
  set_fact: 'rbenv_owner={{ rbenv_owner | default("root", true) }}'
  tags: rbenv

- name: set tmp directory path
  set_fact: rbenv_tmpdir="{{ ansible_env.TMPDIR | default('/tmp') }}"
  when: rbenv_tmpdir is undefined
  tags: rbenv

- include: system_install.yml
  when: rbenv.env == "system"
  tags: rbenv

- include: user_install.yml
  when: rbenv.env != "system"
  tags: rbenv
